version: '3.4'

services:
  motorcycledeliveryrentwebapi:
    image: ${DOCKER_REGISTRY-}motorcycledeliveryrentwebapi
    build:
      context: .
      dockerfile: MotorcycleDeliveryRentWebAPI/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: DB_Motorbike_Rental
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:


# mongodb://admin:admin@localhost:27017  #RabbitMQ    http://localhost:15672